#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Scheduler - Runs scheduled tasks for AI Employee.

Supports:
- Daily briefings
- Weekly audits
- Custom scheduled tasks
- Windows Task Scheduler integration
- Linux/Mac cron integration

Usage:
    python scheduler.py /path/to/vault --task daily_briefing
    python scheduler.py /path/to/vault --task weekly_audit
    python scheduler.py /path/to/vault --install-windows
    python scheduler.py /path/to/vault --install-cron
"""

import sys
import subprocess
import json
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, List, Optional

# Add parent directory for imports
sys.path.insert(0, str(Path(__file__).parent))
from base_watcher import logging


class Scheduler:
    """
    Scheduler for AI Employee recurring tasks.
    """
    
    def __init__(self, vault_path: str):
        """
        Initialize the scheduler.
        
        Args:
            vault_path: Path to the Obsidian vault
        """
        self.vault_path = Path(vault_path)
        self.logger = logging.getLogger(self.__class__.__name__)
        
        # Directories
        self.briefings = self.vault_path / 'Briefings'
        self.logs = self.vault_path / 'Logs'
        self.done = self.vault_path / 'Done'
        self.needs_action = self.vault_path / 'Needs_Action'
        
        # Ensure directories exist
        for directory in [self.briefings, self.logs, self.done]:
            directory.mkdir(parents=True, exist_ok=True)
        
        # Config
        self.config_path = Path(__file__).parent / 'scheduler_config.json'
        self.config = self._load_config()
    
    def _load_config(self) -> Dict:
        """Load scheduler configuration."""
        if self.config_path.exists():
            with open(self.config_path, 'r') as f:
                return json.load(f)
        return {}
    
    def run_task(self, task_name: str, **kwargs) -> bool:
        """
        Run a scheduled task.
        
        Args:
            task_name: Name of the task to run
            **kwargs: Additional arguments
            
        Returns:
            True if successful
        """
        self.logger.info(f'Running scheduled task: {task_name}')
        
        tasks = {
            'daily_briefing': self.daily_briefing,
            'weekly_audit': self.weekly_audit,
            'process_pending': self.process_pending,
            'cleanup_old_files': self.cleanup_old_files,
        }
        
        if task_name not in tasks:
            self.logger.error(f'Unknown task: {task_name}')
            return False
        
        try:
            return tasks[task_name](**kwargs)
        except Exception as e:
            self.logger.error(f'Task failed: {e}', exc_info=True)
            return False
    
    def daily_briefing(self) -> bool:
        """
        Generate daily briefing.
        
        Returns:
            True if successful
        """
        today = datetime.now()
        briefing_path = self.briefings / f'{today.strftime("%Y-%m-%d")}_Briefing.md'
        
        # Count tasks
        done_count = len(list(self.done.glob('*.md')))
        pending_count = len(list(self.needs_action.glob('*.md')))
        
        # Get today's date range
        today_str = today.strftime('%B %d, %Y')
        
        content = f'''---
generated: {today.isoformat()}
type: daily_briefing
date: {today.strftime("%Y-%m-%d")}
---

# Daily Briefing - {today_str}

## Overview

Good morning! Here's your daily summary.

## Task Summary

| Metric | Count |
|--------|-------|
| Completed (all time) | {done_count} |
| Pending | {pending_count} |

## Today's Date

**{today.strftime("%A, %B %d, %Y")}**

## Suggested Focus Areas

1. Review pending items in Needs_Action folder
2. Check for any urgent emails or messages
3. Process any pending approvals
4. Update business goals if needed

## Quick Links

- [Pending Actions](../Needs_Action/)
- [Pending Approvals](../Pending_Approval/)
- [Dashboard](../Dashboard.md)
- [Business Goals](../Business_Goals.md)

---
*Generated by AI Employee Scheduler*
'''
        
        briefing_path.write_text(content, encoding='utf-8')
        self.logger.info(f'Daily briefing created: {briefing_path.name}')
        
        self._log_task('daily_briefing', {
            'briefing_file': str(briefing_path),
            'completed_tasks': done_count,
            'pending_tasks': pending_count
        })
        
        return True
    
    def weekly_audit(self) -> bool:
        """
        Generate weekly audit report.
        
        Returns:
            True if successful
        """
        today = datetime.now()
        last_week = today - timedelta(days=7)
        
        audit_path = self.briefings / f'{today.strftime("%Y-%m-%d")}_Weekly_Audit.md'
        
        # Count files created in last 7 days
        recent_done = [f for f in self.done.glob('*.md') 
                      if datetime.fromtimestamp(f.stat().st_mtime) > last_week]
        
        content = f'''---
generated: {today.isoformat()}
type: weekly_audit
period_start: {last_week.strftime("%Y-%m-%d")}
period_end: {today.strftime("%Y-%m-%d")}
---

# Weekly Audit Report

## Period

{last_week.strftime("%B %d")} to {today.strftime("%B %d, %Y")}

## Summary

| Metric | Value |
|--------|-------|
| Tasks Completed | {len(recent_done)} |
| Average per Day | {len(recent_done) // 7} |

## Completed This Week

'''
        
        # List recent completions
        for f in sorted(recent_done, key=lambda x: x.stat().st_mtime, reverse=True)[:10]:
            content += f'- {f.stem}\n'
        
        if not recent_done:
            content += '- *(No tasks completed this week)*\n'
        
        content += f'''

## Recommendations

1. Review pending items and clear backlog
2. Update Business Goals progress
3. Check for expired approvals
4. Plan next week's priorities

## Next Week's Focus

- [ ] Set weekly goals
- [ ] Schedule important meetings
- [ ] Review and prioritize pending items

---
*Generated by AI Employee Scheduler*
'''
        
        audit_path.write_text(content, encoding='utf-8')
        self.logger.info(f'Weekly audit created: {audit_path.name}')
        
        self._log_task('weekly_audit', {
            'audit_file': str(audit_path),
            'tasks_completed': len(recent_done),
            'period': f'{last_week.strftime("%Y-%m-%d")} to {today.strftime("%Y-%m-%d")}'
        })
        
        return True
    
    def process_pending(self) -> bool:
        """
        Process all pending items.
        
        Returns:
            True if successful
        """
        pending = list(self.needs_action.glob('*.md'))
        
        self.logger.info(f'Found {len(pending)} pending item(s)')
        
        # This would typically trigger the orchestrator
        # For now, just log
        self._log_task('process_pending', {
            'pending_count': len(pending)
        })
        
        return True
    
    def cleanup_old_files(self, days: int = 30) -> bool:
        """
        Move old completed tasks to archive.
        
        Args:
            days: Move files older than this many days
            
        Returns:
            True if successful
        """
        cutoff = datetime.now() - timedelta(days=days)
        moved = 0
        
        archive_dir = self.vault_path / 'Archive'
        archive_dir.mkdir(parents=True, exist_ok=True)
        
        for f in self.done.glob('*.md'):
            file_time = datetime.fromtimestamp(f.stat().st_mtime)
            if file_time < cutoff:
                # Move to archive
                new_path = archive_dir / f.name
                f.rename(new_path)
                moved += 1
        
        self.logger.info(f'Moved {moved} old file(s) to archive')
        
        self._log_task('cleanup_old_files', {
            'files_moved': moved,
            'days_threshold': days
        })
        
        return True
    
    def _log_task(self, task_name: str, details: Dict):
        """Log task execution."""
        today = datetime.now().strftime('%Y-%m-%d')
        log_file = self.logs / f'{today}.json'
        
        log_entry = {
            'timestamp': datetime.now().isoformat(),
            'action_type': 'scheduled_task',
            'task_name': task_name,
            'actor': 'scheduler',
            **details
        }
        
        if log_file.exists():
            content = log_file.read_text(encoding='utf-8').strip()
            if content.endswith(']'):
                content = content[:-1].rstrip()
                if not content.endswith('['):
                    content += ','
                content += '\n  ' + str(log_entry).replace("'", '"') + '\n]'
        else:
            content = '[\n  ' + str(log_entry).replace("'", '"') + '\n]'
        
        log_file.write_text(content, encoding='utf-8')
    
    def install_windows_task(self):
        """Install Windows Task Scheduler tasks."""
        script_dir = Path(__file__).parent
        python_exe = sys.executable
        
        tasks = [
            {
                'name': 'AI Employee Daily Briefing',
                'time': '08:00',
                'args': f'{script_dir}\\scheduler.py {self.vault_path} --task daily_briefing'
            },
            {
                'name': 'AI Employee Weekly Audit',
                'time': '09:00',
                'day': 'MONDAY',
                'args': f'{script_dir}\\scheduler.py {self.vault_path} --task weekly_audit'
            }
        ]
        
        print('\n📋 Windows Task Scheduler Installation')
        print('=' * 50)
        print('\nTo install scheduled tasks, run these commands in PowerShell (as Administrator):\n')
        
        for task in tasks:
            day_filter = f'/D {task["day"]}' if 'day' in task else ''
            print(f'# {task["name"]}')
            print(f'schtasks /Create /TN "{task["name"]}" /TR "{python_exe} {task["args"]}" /SC DAILY {day_filter} /ST {task["time"]} /RL HIGHEST /F')
            print()
        
        print('\nOr use the GUI:')
        print('1. Open Task Scheduler (taskschd.msc)')
        print('2. Click "Create Basic Task"')
        print('3. Follow the wizard for each task above')
    
    def install_cron(self):
        """Install cron tasks for Linux/Mac."""
        script_dir = Path(__file__).parent
        python_exe = sys.executable
        
        print('\n📋 Cron Installation')
        print('=' * 50)
        print('\nAdd these lines to your crontab (run `crontab -e`):\n')
        
        print(f'# Daily Briefing at 8 AM')
        print(f'0 8 * * * {python_exe} {script_dir}/scheduler.py {self.vault_path} --task daily_briefing')
        print()
        print(f'# Weekly Audit every Monday at 9 AM')
        print(f'0 9 * * 1 {python_exe} {script_dir}/scheduler.py {self.vault_path} --task weekly_audit')
        print()


def main():
    """Main entry point."""
    import argparse
    
    parser = argparse.ArgumentParser(description='AI Employee Scheduler')
    parser.add_argument('vault_path', type=str, help='Path to Obsidian vault')
    parser.add_argument('--task', '-t', type=str, 
                       choices=['daily_briefing', 'weekly_audit', 'process_pending', 'cleanup_old_files'],
                       help='Task to run')
    parser.add_argument('--days', type=int, default=30, help='Days threshold for cleanup')
    parser.add_argument('--install-windows', action='store_true', help='Install Windows Task Scheduler')
    parser.add_argument('--install-cron', action='store_true', help='Install cron jobs')
    
    args = parser.parse_args()
    
    vault_path = Path(args.vault_path)
    if not vault_path.exists():
        print(f'Error: Vault path does not exist: {vault_path}')
        sys.exit(1)
    
    scheduler = Scheduler(str(vault_path))
    
    if args.install_windows:
        scheduler.install_windows_task()
    elif args.install_cron:
        scheduler.install_cron()
    elif args.task:
        success = scheduler.run_task(args.task, days=args.days)
        if success:
            print(f'✓ Task "{args.task}" completed successfully')
        else:
            print(f'✗ Task "{args.task}" failed')
            sys.exit(1)
    else:
        parser.print_help()


if __name__ == '__main__':
    main()
